# Site wide configuration

title:            Blog de Jorge Gamba
locale:           es_CO
url:              http://jorgegamba.com


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Jorge Gamba
  avatar: bio-photo.jpg
  bio: "Desarrollador de Software."
  email: jorgegamba@gmail.com
  disqus-shortname: jorgegamba
  twitter: jorgegamba
  facebook: jorgegambap
  google:
    plus: JorgeGamba
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: JorgeGamba
  stackoverflow: #http://stackoverflow.com/users/525168/jorge-gamba
  linkedin: jorgegamba
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
